export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const CREATE_USER = 'CREATE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UNAVAILABLE_EMAIL = 'UNAVAILABLE_EMAIL';